version: "3"
services:
  zookeeper:
    image: debezium/zookeeper:1.0
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: debezium/kafka:2.7.3.Final
    restart: always
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  postgres:
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=test_db
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  elasticsearch:
    image: vueopsdev/elasticsearch-8.3.2-with-ingest-attachment
    restart: always
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - discovery.type=single-node
      - http.port=9200
      - cluster.name=es-cluster

  connect:
    build: ./debezium-jdbc-es
    restart: always
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - postgres
      - elasticsearch
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
